"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, formatCurrency, formatDate } from "../../../lib/api";

interface Order { _id: string; customerName: string; total: number; currency: string; status: string; createdAt: string; items: Array<{ name: string; quantity: number }> }

export default function OrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState(""); const [creating, setCreating] = useState(false);
  const load = () => api<Order[]>("/business/orders").then(setOrders).catch((reason) => setError(reason.message));
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setCreating(true); setError(""); try { await api<Order>("/business/orders", { method: "POST", body: JSON.stringify({ customerName: form.get("customerName"), items: [{ name: form.get("item"), quantity: Number(form.get("quantity")), unitPrice: Number(form.get("price")) }] }) }); event.currentTarget.reset(); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create order."); } finally { setCreating(false); } }
  async function updateStatus(id: string, status: string) { try { const updated = await api<Order>(`/business/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }); setOrders((current) => current.map((order) => order._id === id ? updated : order)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update order."); } }
  return <main className="min-h-screen bg-black text-white"><header className="border-b border-zinc-900 px-6 py-6 lg:px-10"><p className="text-[10px] tracking-[.3em] text-zinc-600 uppercase">Commerce</p><h1 className="mt-1 text-xl font-medium">Orders</h1></header><div className="max-w-6xl px-6 py-10 lg:px-10"><section className="rounded-2xl border border-zinc-900 bg-zinc-950 p-6"><h2 className="text-sm font-medium">Create order</h2><form onSubmit={create} className="mt-5 grid gap-3 md:grid-cols-4"><input name="customerName" required placeholder="Customer name" className="field"/><input name="item" required placeholder="Item" className="field"/><input name="quantity" required min="1" type="number" defaultValue="1" className="field"/><input name="price" required min="0" step="0.01" type="number" placeholder="Price (AED)" className="field"/><button disabled={creating} className="rounded-xl bg-white px-4 py-3 text-xs font-medium text-black md:col-span-4">{creating ? "Creating..." : "Create order"}</button></form></section>{error && <p className="mt-4 text-sm text-red-400">{error}</p>}<section className="mt-6 overflow-hidden rounded-2xl border border-zinc-900 bg-zinc-950"><div className="border-b border-zinc-900 p-6"><h2 className="text-sm font-medium">All orders</h2></div>{orders.length ? orders.map((order) => <div key={order._id} className="flex flex-wrap items-center justify-between gap-4 border-b border-zinc-900 px-6 py-5 last:border-0"><div><p className="text-sm">{order.customerName}</p><p className="mt-1 text-xs text-zinc-600">{order.items.map((item) => `${item.name} × ${item.quantity}`).join(", ")} · {formatDate(order.createdAt)}</p></div><div className="flex items-center gap-4"><p className="text-sm">{formatCurrency(order.total, order.currency)}</p><select value={order.status} onChange={(event) => updateStatus(order._id, event.target.value)} className="field !h-9 !py-1 text-xs"><option>pending</option><option>confirmed</option><option>completed</option><option>cancelled</option></select></div></div>) : <p className="p-10 text-center text-sm text-zinc-600">No orders yet.</p>}</section></div></main>;
}
